{% set name = "coexist" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coexist-{{ version }}.tar.gz
  sha256: c82d659de5d9a2ebeea7490166f44dd1d3e5788dcd831c0940a04b9eb124dd36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.3
    - scipy >=1.4.1
    - pandas >=1.0.5
    - toml >=0.10.2
    - cma >=3.0.3
    - tqdm >=4.41.1
    - astunparse >=1.6.3
    - pyevtk >=1.1.1
    - matplotlib-base >=3.2.1
    - plotly >=4.4.1

test:
  imports:
    - coexist
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uob-positron-imaging-centre/Coexist
  summary: Learning simulation parameters from experimental data, from the micro to the macro, from the laptop to the cluster.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
